-- 飞云公开数据表。请在 Supabase SQL Editor 中执行一次。
-- Publishable key 仅允许读取 active jobs 和 verified talent profiles；
-- 写入必须使用 Supabase Auth 且 app_metadata.role = 'admin'。

create table if not exists public.jobs (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  team text not null,
  domain text not null,
  location text not null,
  employment_type text not null default '全职',
  salary_range text not null default '面议',
  summary text not null,
  requirements text not null default '',
  status text not null default 'active' check (status in ('draft', 'active', 'closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.talent_profiles (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  title text not null,
  domain text not null,
  location text not null default '',
  summary text not null,
  skills text not null default '',
  evidence_count integer not null default 0,
  source_count integer not null default 0,
  match_score integer not null default 80 check (match_score between 0 and 100),
  recent_signal text not null default '',
  verified boolean not null default true,
  updated_at timestamptz not null default now()
);

alter table public.jobs enable row level security;
alter table public.talent_profiles enable row level security;

drop policy if exists "Public can read active jobs" on public.jobs;
create policy "Public can read active jobs"
on public.jobs for select
to anon, authenticated
using (status = 'active');

drop policy if exists "Public can read verified talent" on public.talent_profiles;
create policy "Public can read verified talent"
on public.talent_profiles for select
to anon, authenticated
using (verified = true);

drop policy if exists "Admins manage jobs" on public.jobs;
create policy "Admins manage jobs"
on public.jobs for all
to authenticated
using ((select auth.jwt()->'app_metadata'->>'role') = 'admin')
with check ((select auth.jwt()->'app_metadata'->>'role') = 'admin');

drop policy if exists "Admins manage talent" on public.talent_profiles;
create policy "Admins manage talent"
on public.talent_profiles for all
to authenticated
using ((select auth.jwt()->'app_metadata'->>'role') = 'admin')
with check ((select auth.jwt()->'app_metadata'->>'role') = 'admin');

grant select on public.jobs, public.talent_profiles to anon, authenticated;
grant insert, update, delete on public.jobs, public.talent_profiles to authenticated;
